### ISSUE TITLE
Crash when deforming objects

### ISSUE THREAD

**Issue by hakolao** [hakolao/sandbox#1]
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 2 but the index is 2', /home/okko/.cargo/git/checkouts/parry-cfbedab32ac7a479/d6629d0/build/parry2d/../../src/shape/convex_polygon.rs:131:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/092e1c9d23158d81be27bb6f71bdd0c6282478fb/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/092e1c9d23158d81be27bb6f71bdd0c6282478fb/library/core/src/panicking.rs:110:14
   2: core::panicking::panic_bounds_check
             at /rustc/092e1c9d23158d81be27bb6f71bdd0c6282478fb/library/core/src/panicking.rs:77:5
   3: <parry2d::shape::convex_polygon::ConvexPolygon as parry2d::shape::polygonal_feature_map::PolygonalFeatureMap>::local_support_feature
   4: parry2d::query::contact_manifolds::contact_manifolds_pfm_pfm::contact_manifold_pfm_pfm
   5: <parry2d::query::default_query_dispatcher::DefaultQueryDispatcher as parry2d::query::query_dispatcher::PersistentQueryDispatcher<ManifoldData,ContactData>>::contact_manifold_convex_convex
   6: parry2d::query::contact_manifolds::contact_manifolds_composite_shape_composite_shape::contact_manifolds_composite_shape_composite_shape::{{closure}}::{{closure}}::{{closure}}::{{closure}}
   7: parry2d::query::contact_manifolds::contact_manifolds_composite_shape_composite_shape::contact_manifolds_composite_shape_composite_shape::{{closure}}::{{closure}}
   8: parry2d::partitioning::qbvh::QBVH<T>::traverse_depth_first
   9: parry2d::query::contact_manifolds::contact_manifolds_composite_shape_composite_shape::contact_manifolds_composite_shape_composite_shape
  10: <parry2d::query::default_query_dispatcher::DefaultQueryDispatcher as parry2d::query::query_dispatcher::PersistentQueryDispatcher<ManifoldData,ContactData>>::contact_manifolds
  11: rapier2d::geometry::narrow_phase::NarrowPhase::compute_contacts
  12: rapier2d::pipeline::physics_pipeline::PhysicsPipeline::detect_collisions
  13: rapier2d::pipeline::physics_pipeline::PhysicsPipeline::step
  14: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  15: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  16: rayon_core::registry::WorkerThread::wait_until_cold
  17: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by hakolao** [comment]
Likely fixed, but similar might occur
